language: node_js
node_js:
  - "0.12"

services:
  - mongodb
  - redis-server

before_script:
  - sleep 10
  - npm install

script: "npm run-script test-travis"

after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"